WIDTH, HEIGHT = 800, 600

INITIAL_CHECKING_ACCOUNT = 0
INITIAL_WAGE = 5000
INITIAL_NATIONAL_BANK_INTEREST = 5
INITIAL_PRIME = INITIAL_NATIONAL_BANK_INTEREST + 1.5
SINGULAR_DEPOSIT = 0
MONTHLY_DEPOSIT = 1
DEPOSIT_TYPES = [SINGULAR_DEPOSIT, MONTHLY_DEPOSIT]
FIXED_INTEREST = 0
PRIME_LINKED_INTEREST = 1
INTEREST_TYPES = [FIXED_INTEREST, PRIME_LINKED_INTEREST]

RUNNING_STATE = True

DARK_BLUE = (25,25,112)
DARK_PURPLE = (52,21,57)
BUTTON_X = 300
BUTTON_Y = 300
BUTTON_WIDTH = 200
BUTTON_HEIGHT = 150